const:
  default-page-size : 20


# custom property (???? Absolute Path)
file:
  directory: D:/mydownload/greengram_ver3



# mybatis setting
mybatis:
  mapper-locations: mappers/**/*.xml


spring:
  application:
    name: GreenGramVer3

  # DB setting
  Datasource:
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB


springdoc:
  swagger_ui:
    default-model-expand-depth: 10
    display-request-duration:  true
    operations-sorter: method
    path: /swagger
    groups-order: asc # 정렬(????? ???? ???? ??? ??? ?? ????)
    tags-sorter:  alpha # 태그별로 저장하겠다. abcd

  cache:
    disabled: true # 캐시 지우겠다. 성능향샹

